#!/usr/bin/env python3
"""Audit duplicate source/executable files within a bounded repository depth.

The hotfix is intentionally non-destructive: it does not remove legacy copies or
rewrite assembly/C hot paths. It records exact-content duplicate groups so build,
release, or promotion scripts can avoid executing the same source command family
blindly more than once.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
from collections import defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MAX_DEPTH = 5
SOURCE_SUFFIXES = frozenset({".S", ".c", ".h", ".java", ".kt", ".py", ".s", ".sh"})
SKIP_DIRS = frozenset({".git", ".gradle", ".idea", "build"})
REPORT_CSV = ROOT / "reports" / "duplicate_source_audit.csv"
REPORT_JSON = ROOT / "reports" / "duplicate_source_audit.json"
REPORT_MD = ROOT / "reports" / "duplicate_source_audit.md"


@dataclass(frozen=True)
class DuplicateGroup:
    group_id: str
    sha256: str
    file_count: int
    canonical_path: str
    duplicate_paths: list[str]
    mitigation: str


def relative_depth(path: Path) -> int:
    return len(path.relative_to(ROOT).parts)


def skip_path(path: Path) -> bool:
    return any(part in SKIP_DIRS for part in path.relative_to(ROOT).parts)


def source_files(max_depth: int) -> list[Path]:
    files: list[Path] = []
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        if skip_path(path) or relative_depth(path) > max_depth:
            continue
        if path.suffix in SOURCE_SUFFIXES:
            files.append(path)
    return sorted(files)


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def canonical(paths: list[Path]) -> Path:
    def score(path: Path) -> tuple[int, str]:
        rel = str(path.relative_to(ROOT))
        if rel.startswith("app/") or rel.startswith("scripts/"):
            rank = 0
        elif rel.startswith("Arme/Add/"):
            rank = 1
        elif rel.startswith("BugOrAdd/"):
            rank = 2
        elif rel.startswith("rmr/Rrr/"):
            rank = 3
        else:
            rank = 4
        return rank, rel

    return sorted(paths, key=score)[0]


def build_groups(max_depth: int) -> list[DuplicateGroup]:
    by_hash: dict[str, list[Path]] = defaultdict(list)
    for path in source_files(max_depth):
        by_hash[digest(path)].append(path)

    groups: list[DuplicateGroup] = []
    index = 1
    for sha, paths in sorted(by_hash.items(), key=lambda item: (-len(item[1]), str(item[1][0]))):
        if len(paths) < 2:
            continue
        owner = canonical(paths)
        duplicates = [str(path.relative_to(ROOT)) for path in sorted(paths) if path != owner]
        groups.append(
            DuplicateGroup(
                group_id=f"DUP{index:03d}",
                sha256=sha,
                file_count=len(paths),
                canonical_path=str(owner.relative_to(ROOT)),
                duplicate_paths=duplicates,
                mitigation="Do not execute/build every copy blindly; pick canonical or require explicit legacy allowlist.",
            )
        )
        index += 1
    return groups


def write_reports(groups: list[DuplicateGroup], max_depth: int) -> None:
    REPORT_JSON.write_text(json.dumps([asdict(group) for group in groups], ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    with REPORT_CSV.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["group_id", "sha256", "file_count", "canonical_path", "duplicate_paths", "mitigation"])
        for group in groups:
            writer.writerow([group.group_id, group.sha256, group.file_count, group.canonical_path, ";".join(group.duplicate_paths), group.mitigation])
    lines = [
        "# Duplicate Source Audit",
        "",
        f"Generated by `python3 scripts/audit_duplicate_sources.py --max-depth {max_depth}`.",
        "This is a non-destructive hotfix report: duplicate legacy source files are not removed.",
        "",
        "## Summary",
        "",
        f"- Duplicate groups: {len(groups)}",
        f"- Duplicate files beyond canonical owners: {sum(group.file_count - 1 for group in groups)}",
        "",
        "## Groups",
        "",
        "| Group | Count | Canonical | Duplicates | Mitigation |",
        "|---|---:|---|---|---|",
    ]
    for group in groups:
        lines.append(
            f"| {group.group_id} | {group.file_count} | `{group.canonical_path}` | `{'; '.join(group.duplicate_paths)}` | {group.mitigation} |"
        )
    REPORT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--max-depth", type=int, default=DEFAULT_MAX_DEPTH)
    parser.add_argument("--fail-on-duplicates", action="store_true", help="Return 1 if duplicate groups are present.")
    args = parser.parse_args()

    groups = build_groups(args.max_depth)
    write_reports(groups, args.max_depth)
    duplicate_files = sum(group.file_count - 1 for group in groups)
    print(f"duplicate source groups: {len(groups)}")
    print(f"duplicate files beyond canonical: {duplicate_files}")
    return 1 if args.fail_on_duplicates and groups else 0


if __name__ == "__main__":
    raise SystemExit(main())
